# Prometheus 配置文件 - AI问答平台监控

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 后端API监控
  - job_name: 'qa-platform-backend'
    static_configs:
      - targets: ['backend:8088']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis监控 (如果Redis启用了metrics)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # 前端服务监控 (Nginx状态)
  - job_name: 'qa-platform-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # 系统监控 (Node Exporter - 可选)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

# 告警规则 (可选)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
